//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Routes
    {
        
        public int route_id { get; set; }
        [DisplayName("Маршруты")]
        public string route_name { get; set; }
        public int departure_id { get; set; }
        public int destination_id { get; set; }
        public double price { get; set; }
        public Nullable<int> sights_id { get; set; }
        public double flight { get; set; }
    
       
        public virtual Departure Departure { get; set; }
        public virtual Destination Destination { get; set; }
    }
}
