//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Web.Mvc;

    public partial class TouristicEntities : DbContext
    {
        public TouristicEntities()
            : base("name=TouristicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departure> Departure { get; set; }
        public virtual DbSet<Destination> Destination { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Sights> Sights { get; set; }
    }

    public class RoutesList
    {
        public SelectList Routes { get; set; }
        public SelectList Departure { get; set; }
        public SelectList Destination { get; set; }
    }
}
